<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDnvEh6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDnvEh6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDnvEh6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDnvEh6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXDnvEh6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XDnvEh6',
    'container.build_id' => '37264d96',
    'container.build_time' => 1619383000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDnvEh6');
