<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publication extends \App\Entity\Publication implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'idPub', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'nbcomment', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'contenu', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'datePublication', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'urlimage', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'iduser', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'commentaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'idPub', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'nbcomment', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'contenu', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'datePublication', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'urlimage', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'iduser', '' . "\0" . 'App\\Entity\\Publication' . "\0" . 'commentaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Publication $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPub(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPub();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPub', []);

        return parent::getIdPub();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPub(int $idPub): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPub', [$idPub]);

        parent::setIdPub($idPub);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', []);

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu(string $contenu): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', [$contenu]);

        parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePublication(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePublication', []);

        return parent::getDatePublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePublication(\DateTime $datePublication): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePublication', [$datePublication]);

        parent::setDatePublication($datePublication);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile($image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlimage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlimage', []);

        return parent::getUrlimage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlimage($urlimage): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlimage', [$urlimage]);

        parent::setUrlimage($urlimage);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduser(): ?\App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduser', []);

        return parent::getIduser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduser(\App\Entity\Utilisateur $iduser): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduser', [$iduser]);

        parent::setIduser($iduser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbcomment(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbcomment', []);

        return parent::getNbcomment();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbcomment(int $nbcomment): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbcomment', [$nbcomment]);

        parent::setNbcomment($nbcomment);
    }

}
